### ISSUE TITLE
Add metadata about various models

### ISSUE THREAD

**Issue by neubig** [nightingal3/llm-pretraining-behaviours#29]
It would be nice to have metadata about various models available so we can associate this metadata with model performance.

I will start by trying to get all of the models and metadata in the OLMo paper incorporated in the `metadata` directory in JSON format.

![Screenshot 2024-03-07 at 8 28 44 AM](https://github.com/nightingal3/llm-pretraining-behaviours/assets/398875/e538f4f3-5547-4089-aef8-3d1679361ee9)

(but PaLM-8B is not public so skip that)

## Tasks

- [ ] Create metadata scraper from hugging face (#27)
- [ ] Create validation script (#33)
- [ ] Scrape all the models included in OLMo and add the metadata that is included in this table
